config/routes.rb
Rails.application.routes.draw do
  root to: 'companies#index'
  resources :companies
  resources :insiders
  resources :trades
end

app/models/company.rb
# == Schema Information
#
# Table name: companies
#
#  id         :integer          not null, primary key
#  ticker     :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Company < ActiveRecord::Base
  has_many :trades
end

app/models/insider.rb
# == Schema Information
#
# Table name: insiders
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Insider < ActiveRecord::Base
  has_many :trades
end

app/models/trade.rb
# == Schema Information
#
# Table name: trades
#
#  id         :integer          not null, primary key
#  shares     :integer
#  company_id :integer
#  insider_id :integer
#  created_at :datetime
#  updated_at :datetime
#

class Trade < ActiveRecord::Base
  belongs_to :insider
  belongs_to :company
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end
end

app/controllers/insiders_controller.rb
class InsidersController < ApplicationController
  def index
    @insiders = Insider.all
  end

  def show
    @insider = Insider.find(params[:id])
  end
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  def index
    @trades = Trade.all
  end

  def show
    @trade = Trade.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/insiders_helper.rb
module InsidersHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/companies/_company.html.erb
<%= link_to company.ticker, company %><br>

app/views/companies/index.html.erb
<h1>Companies</h1>

<%= render @companies %>

app/views/companies/show.html.erb
<h1><%= @company.ticker %></h1>

<%= render @company.trades %>

<br>
<%= link_to "Companies", companies_url %>

app/views/insiders/_insider.html.erb
<%= link_to insider.name, insider %><br>

app/views/insiders/index.html.erb
<h1>Insiders</h1>

<%= render @insiders %>

<br>
<%= link_to "Insiders", insiders_url %>

app/views/insiders/show.html.erb
<h1><%= @insider.name %></h1>
<%= render @insider.trades %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Poly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/trades/_trade.html.erb
<%= link_to "Trade #{ trade.id }", trade %>

app/views/trades/index.html.erb
<h1>Trades</h1>

<%= render @trades %>

app/views/trades/show.html.erb
<h1>Trades</h1>

<%= @trade.shares %>

<%= render @trade.company %>
<%= render @trade.insider %>